name: xox_case_study
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Core
  uuid: ^4.4.2
  fluttertoast: ^8.2.5

  #State Management
  get: ^4.6.6

  #Network
  dio: ^5.5.0+1

  #Cache
  hive_flutter: ^1.1.0

  #Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1

  #UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
